service: mac-bkk-waterflood-warning-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  rateHandler:
    handler: index.run
    events:
      - schedule: rate(3 hours)
